# Generated by Django 4.1.7 on 2023-03-27 03:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='Kompaniya nomi')),
                ('about', models.TextField(verbose_name='Kompaniya haqida')),
                ('logo', models.TextField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
